application:
  audience: ${env.AUTH0_AUDIENCE}
  client-origin-url: ${env.CLIENT_ORIGIN_URL}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/webstore
    hikari:
      schema: webstore
  liquibase:
    changeLog: classpath:/db.changelog/liquibase-changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${env.AUTH0_DOMAIN}/
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false
  port: ${env.PORT}
